### ISSUE TITLE
Deployment to AWS S3 - CSS is not rendering properly

### ISSUE THREAD

**Issue by damianesteban** [octopress/octopress#144]
I am attempting to deploy my Jekyll/Octopress 3.0 static site to an Amazon S3 bucket.
Following the instructions in the repository, I'm using the `aws-sdk-v1` gem.

In my _deploy.yml file, I have the headers configured as follows:
```
headers:
   - filename: '^assets.*\.js$'
     expires: '+3 years'
     cache_control: 'max-age=94608000'
     content_type: 'application/javascript'
   - filename: '^assets.*\.css$'
     expires: '+3 years'
     cache_control: 'max-age=94608000'
     content_type: 'text/css'
```
In the AWS web console, the metadata of my CSS file is `text/css`.

Does anyone know what may be causing the issue?  Perhaps I should use Octopress 2 for now?
