### ISSUE TITLE
Author is not link

### ISSUE THREAD

**Issue by onmyway133** [octopress/octopress#149]
I'm using octopress and really happy with it. There 's just one thing. Here is my `author` section in `_config.yml`

```
authors:
  onmyway133:
    display_name: Khoa Pham
    email: onmyway133@gmail.com
    web: https://twitter.com/onmyway133
    twitter: onmyway133
    github: onmyway133
```

And I already use that handle in my post

```
---
author: onmyway133
layout: post
title: "A sample post"
date: 2015-11-05 00:32:57 +0700
comments: true
categories:
---
```

After `git add`, `git commit`, `git push`, `rake generate`, `rake deploy` I see that my name is just text, not link, I suppose it will link to `web` in my `author` section

You can see `http://www.fantageek.com/blog/2015/11/05/a-dream-company/`, it is just text `onmyway133`
