### ISSUE TITLE
Canonical URL showing localhost:4000 in production URL

### ISSUE THREAD

**Issue by VincentTam** [octopress/octopress#181]
I'm testing Octopress 3.  I uploaded a minimal example on VincentTam/octo3test.  In `index.html` on the `gh-pages` branch, the [canonical link reads `localhost`](https://git.io/vM2wx).

```html
<link rel="stylesheet" href="/octo3test/assets/main.css">
<link rel="canonical" href="http://localhost:4000/octo3test/">
<link rel="alternate" type="application/rss+xml" title="Your awesome title" href="/octo3test/feed.xml">
```

In my `_config.yml`, I set

```yml
baseurl: "/octo3test"
url: "http://vincenttam.github.io"
```

(I carelessly missed an 's'.)

and my `_deploy.yml`

```yml
method: git                               # How do you want to deploy? git, rsync or s3.
site_dir: _site                           # Location of your static site files.

git_url: git@github.com:VincentTam/octo3test.git  # remote repository url, e.g. git@github.com:username/repo_name

# Note on git_branch:
# If using GitHub project pages, set the branch to 'gh-pages'.
# For GitHub user/organization pages or Heroku, set the branch to 'master'.
#
git_branch: gh-pages                        # Git branch where static site files are commited


# remote_path:                            # Destination directory
```
