### ISSUE TITLE
Octopress deploy fatal: pathspec ':/' did not match any files

### ISSUE THREAD

**Issue by emad-elsaid** [octopress/octopress#46]
i tried to create a new octopress blog, and pushing it to my github https://github.com/blazeeboy/blazeeboy.github.io using the following steps :

``` bash
$ gem install octopress --pre
$ octopress new blazeboy
$ cd blazeboy
// then replaced the theme with scrubble
$ gem install octopress-deploy --pre
$ octopress deploy init git
$ octopress build
$ octopress deploy
```

the `octopress deploy` step prints the following error

```
Syncing _site files to git@github.com:blazeeboy/blazeeboy.github.io.git.
From github.com:blazeeboy/blazeeboy.github.io
 * branch            master     -> FETCH_HEAD
fatal: pathspec ':/' did not match any files
Everything up-to-date
```

so i tried the following:

``` bash
$ cd .deploy
$ git add .
$ git commit -m"my message"
$ git push deploy
```

and it worked fine and pushed the site. https://github.com/blazeeboy/blazeeboy.github.io
now, i tried to modify a post and the following.

``` bash
$ octopress build
$ octopress deploy
```

and it prints the same error message and doesn't commit or push anything.
my `_deploy.yml` file content is:

``` yaml
method: git                               # How do you want to deploy? git, rsync or s3.
site_dir: _site                           # Location of your your static site files.

git_url:  git@github.com:blazeeboy/blazeeboy.github.io.git

# Note on git_branch:
# If using GitHub project pages, set the branch to 'gh-pages'.
# For GitHub user/organization pages or Heroku, set the branch to 'master'.
#
git_branch: master                        # Git branch where static site files are commited


# remote_path:                            # Destination directory
```

and my `_config.yml` content:

``` yaml
# Site settings
title: Blaze Boy
email: blazeeboy@gmail.com
description: "Software Engineer and Particularly a Ruby Addict"
baseurl: ''
url: "http://www.blazeboy.me"
signoff: 'E.E'

# Build settings
markdown: kramdown
permalink: /:title.html

disqus_shortname: blazeboy
facebook_appid:   1400091873588797
google_analytics: UA-53753121-1

links:
  - name:         About
    url:          /about
  - name:         Home
    url:          /
  - name:         Facebook
    url:          https://www.facebook.com/blazeeboy
    external:     true
  - name:         GitHub
    url:          https://github.com/blazeeboy
    external:     true
```

is there something i'm missing ?
