### ISSUE TITLE
Category generator gem

### ISSUE THREAD

**Issue by gntech** [octopress/octopress#90]
Is there plans/work going on to make a gem out of the category_generator plugin found in octopress 2.0 ?

https://github.com/imathis/octopress/blob/master/plugins/category_generator.rb

Let me know if I can help out with it otherwise

**Comment by drallgood** [comment]
I'm working on that right now...

There are a few issues regarding Octopress::Page vs. Jekyll:Page though (not sure which one I should use...)

**Comment by imathis** [comment]
I have plans to work on a category generator gem. Originally I thought it would have to be shipped with a theme, but I think I can release it separately.

**Comment by drallgood** [comment]
@imathis I'm in the process of migrating the existing plugin and making it compatible with ink and multilingual.
Thought that was a fun thing to do :wink: 

If you like, I can send you the finished plugin once I'm done 
(Right now I'm pondering whether it would be nice for the generated pages to show up if you do an `octopress ink list categories, but other than that it's almost done)

**Comment by gntech** [comment]
Just for information, There is a similar gem called https://github.com/jekyll/jekyll-archives . It doesnt work quite the same as the category_generator plugin but I have achieved similar results with both after some tweaking. 
Maybe an octopress category generator could be based on jekyll-archives?

**Comment by drallgood** [comment]
A little status update:

I'm almost done. I went with the solution where pages also show up in the ink list.

Here's an example output:
```
Plugin: Octopress Categories - v0.0.1
Slug: categories
Category pages for Octopress and Jekyll pages.
================================================================================
 layouts:
  - category_feed.xml
  - category_index.html

 config:
   category_dir: "categories"
   prefixes: 
     title: "Category: "
     meta_description: "Category: "
   feed: 
     enabled: false
     count: 5
   permalinks:

 category-pages:
  - announcements-de                   /de/categories/announcements/
  - blogging-de                        /de/categories/blogging/
  - howto-de                           /de/categories/howto/
  - opinion-de                         /de/categories/opinion/
  - apple-de                           /de/categories/apple/
  - developer-de                       /de/categories/developer/
  - apps-de                            /de/categories/apps/
  - review-de                          /de/categories/review/
  - announcements-en                   /en/categories/announcements/
  - blogging-en                        /en/categories/blogging/
  - howto-en                           /en/categories/howto/
  - opinion-en                         /en/categories/opinion/
  - apple-en                           /en/categories/apple/
  - developer-en                       /en/categories/developer/
  - apps-en                            /en/categories/apps/
  - review-en                          /en/categories/review/
```

Those pages are NOT copied when you copy the assets to `_plugins/categories/`
Feeds are still missing. Trying to work out, how to do it properly...

@imathis: If you like, I can turn over the code to you now (it's basically your code anyway).
