### ISSUE TITLE
Don’t force layout into page and post YAML if templates exclude it.

### ISSUE THREAD

**Issue by matthewmcvickar** [octopress/octopress#99]
**I'd like to be to configure `octopress new` to generate the page or post without adding `layout: page` or `layout: post` to the YAML front matter.**

I have YAML front matter defaults set in my `_config.yml` so that these settings are not necessary on every post and page:

```yaml
# YAML Front Matter Defaults
defaults:

  # Automatically set the layout for pages and posts.
  -
    scope:
      type: 'pages'
    values:
      layout: 'page'
  -
    scope:
      type: 'posts'
    values:
      layout: 'post'
```

Accordingly, I've changed my templates in `/_templates/` to exclude the `layout:` portion, but the `octopress new` command appends them to the YAML front matter anyway.

Can there be a configuration setting to ignore the `layout` setting if either the templates exclude that parameter or if, say, the settings are blank in `_config.yml`? I.e.:

```yaml
post_ext:    'md'
page_layout: ''
post_layout: ''
```
